name: Demo <gh-pages>

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Aggregator UI
        env:
          VITE_DEPLOY_PATH: '/fcs-sru-aggregator-ui'
          VITE_API_URL: 'https://contentsearch.clarin.eu/rest/'
          VITE_CANONCIAL_URL: 'https://contentsearch.clarin.eu'
          VITE_VALIDATOR_URL: 'https://www.clarin.eu/fcsvalidator/'
          VITE_I18N_NS_CONTEXT_PREFIX: 'clarin'
          VITE_LOCALES: '["en", "de"]'
          VITE_LOCALE: 'en'
        run: npm run build

      - name: Store build artifact
        uses: actions/upload-artifact@v4
        with:
          name: aggregator-ui
          path: dist/*

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v4
        with:
          name: aggregator-ui
          path: build

      - name: Push generated files to branch 'gh-pages'
        if: ${{ success() }}
        run: |
          mkdir -p static
          mv -v build/* static/
          cd static
          git init -b main
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[release] Publish on GitHub Pages"
          git push --force origin main:gh-pages
